### ISSUE TITLE
Broken reference link

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/geosemantics-dwg#20]
The URI http://www.data-intelligence-journal.org/p/24/#Ch-S2 in [the White Paper's references doc](https://github.com/opengeospatial/geosemantics-dwg/blob/master/white_paper/annex-bibliography.adoc) is broken.

**Comment by jabhay** [comment]
Hi @nicholascar, is the issue here that the reference links to Ch-S2, in which case http://www.data-intelligence-journal.org/p/24/ is preferred?
