### ISSUE TITLE
Too many similar examples

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/geosemantics-dwg#23]
Many of the Use Cases mention the Optique platform and use the acronym VKG, which I've not hear before, so it's obvious that they have all been source from one similar place. I suggest some of them are replaced with different Use Cases and different approaches/tools.

**Comment by jabhay** [comment]
This is an excellent idea +1

**Comment by FransKnibbe** [comment]
In the teleconference of 2019-12-17 there was talk of additional use cases that could be added, especially use cases featuring non-geographic semantic/graph data. Have any of them materialised already?

**Comment by jabhay** [comment]
Yes @FransKnibbe , I've added a few of them now, and have removed a few of the older use cases  (PR ready for review). It may be worth assigning this back to @nicholascar to check out the PR and see whether he's happy with the current state of the use cases.
