### ISSUE TITLE
Any Contact Tracing Use Case for HealthCare?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/geosemantics-dwg#94]
GeoSPARQL combines both the graph structure and location referencing, so potentially it could be useful for assisting Contact Tracing in COVID-19 response (or in response to any outbreak).

Perhaps also make reference to the Health SDI White Paper http://docs.opengeospatial.org/wp/19-076.html

**Comment by jabhay** [comment]
Hi @ghobona , 

Thanks for adding this. 

If you have a contact tracing use case to add to the white paper, I'd be happy to approve a PR. Please keep in mind that the use case section is aimed at demonstrating operational real world applications of graph and semantic technologies to raise awareness of the existing use of these technologies, and not demonstrating potential applications.

Same goes for the reference to the Health SDI White Paper - if there's content in that paper that strengthens the white paper's description of the benefits of representing spatial data using graph or semantic technologies, I'd happily approve a PR with content in the document and a reference in the bibliography. 

Please respond by either closing this issue, or adding a PR or two for us to review and approve. I'm keen to get the white paper out to assist the awareness raising necessary to support the GeoSPARQL SWG Charter vote :)

Cheers,
Jo

**Comment by ghobona** [comment]
Information about contact tracing systems tends to be sensitive, so one is unlikely to find detailed descriptions of "operational real world applications" or be in a position to share them.
